[
  ./acpid.nix
  ./avizo.nix
  ./flameshot.nix
  ./greetd.nix
  ./lid.nix
  ./picom.nix
  ./polybar.nix
  ./redshift.nix
  ./swaync/swaync-oglo.nix
  ./swaync/swaync-dynamic.nix
  ./sxhkd.nix
  ./syncthing.nix
  ./udiskie.nix
  ./wlsunset.nix
]
