[
  ./waybar-cool.nix
  ./waybar-curve.nix
  ./waybar-ddubs.nix
  ./waybar-dwm.nix
  ./waybar-jake.nix
  ./waybar-jerry.nix
  ./waybar-macos.nix
  ./waybar-nekodyke.nix
  ./waybar-oglo.nix
  ./waybar-simple.nix
]
