[
  ./ags.nix
  ./alacritty.nix
  ./android.nix
  ./anyrun.nix
  ./bat.nix
  ./btop.nix
  ./cava.nix
  ./chrome.nix
  ./distrobox.nix
  ./eww.nix
  ./eza.nix
  ./fastfetch.nix
  ./fhs.nix
  ./firefox.nix
  ./games.nix
  ./htop.nix
  ./hyprpanel.nix
  # ./jovian.nix
  ./kdeconnect.nix
  ./kitty.nix
  ./mithril.nix
  # ./pcmanfm.nix
  ./rofi/rofi-oglo.nix
  ./rofi/rofi-zaney.nix
  ./spicetify.nix
  ./swappy.nix
  ./thunar.nix
  ./tmux.nix
  ./waybar/waybar-oglo.nix
  ./waybar/waybar-zaney.nix
  ./waydroid.nix
  ./wine.nix
  ./wlogout.nix
  ./wofi.nix
  ./xdg.nix
]
