[
	./wine.nix
  ./flatpak.nix
  ./distrobox-podman.nix
  ./nur.nix
  ./waydroid/waydroid.nix
	./vm.nix
	./kitty.nix
	#./alacritty.nix
	./wlogout/wlogout.nix
	./appimage.nix
	./waybar/waybar-test.nix
	./rofi.nix
	./packages.nix
	./nautilus.nix
	./zathura.nix
	#./eww.nix
	./htop.nix
	#./firefox.nix
	./spicetify.nix
]
