[
	./wine.nix
  ./flatpak.nix
  ./distrobox-podman.nix
  ./nur.nix
  ./waydroid/waydroid.nix
	./vm.nix
	./kitty.nix
	#./alacritty.nix
	./wlogout/wlogout.nix
	./appimage.nix
	./waybar/waybar-gruvbox.nix
	./rofi/rofi-gruvbox.nix
	./packages.nix
	./thunar.nix
]
